"""postdocs: added column is_graduated

Revision ID: 0ab4077e113a
Revises: add60aed75f6
Create Date: 2025-11-23 15:01:17.869595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab4077e113a'
down_revision: Union[str, None] = 'add60aed75f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postdocs', sa.Column('is_graduated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postdocs', 'is_graduated')
    # ### end Alembic commands ###
