"""change credit_points to numeric

Revision ID: 230dea8df773
Revises: 0ab4077e113a
Create Date: 2026-02-19 09:45:50.393417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230dea8df773'
down_revision: Union[str, None] = '0ab4077e113a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('credit_points',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('credit_points',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
