"""add new automation flags and error handling columns to media and academic publication tables as well as AIRecommendation enum

Revision ID: 238a9f14c9ea
Revises: 8c112bc6bb25
Create Date: 2026-08-14 17:13:53.111836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238a9f14c9ea'
down_revision: Union[str, None] = '8c112bc6bb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_recommendation', sa.Enum('RELEVANT', 'IRRELEVANT', 'UNCERTAIN', name='airecommendation'), nullable=True))
        batch_op.add_column(sa.Column('entities_matched', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_processing_error', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('processing_error_msg', sa.Text(), nullable=True))
        batch_op.drop_column('is_pushed_to_wp')

    with op.batch_alter_table('media_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_scraped', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_recommendation', sa.Enum('RELEVANT', 'IRRELEVANT', 'UNCERTAIN', name='airecommendation'), nullable=True))
        batch_op.add_column(sa.Column('entities_matched', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_processing_error', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('processing_error_msg', sa.Text(), nullable=True))
        batch_op.drop_column('is_pushed_to_wp')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pushed_to_wp', sa.BOOLEAN(), nullable=False, server_default='0'))
        batch_op.drop_column('processing_error_msg')
        batch_op.drop_column('has_processing_error')
        batch_op.drop_column('entities_matched')
        batch_op.drop_column('ai_recommendation')
        batch_op.drop_column('is_scraped')

    with op.batch_alter_table('academic_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pushed_to_wp', sa.BOOLEAN(), nullable=False, server_default='0'))
        batch_op.drop_column('processing_error_msg')
        batch_op.drop_column('has_processing_error')
        batch_op.drop_column('entities_matched')
        batch_op.drop_column('ai_recommendation')

    # ### end Alembic commands ###
