"""add new columns

Revision ID: 392c03db99c8
Revises: d44955f924a7
Create Date: 2025-06-04 18:21:42.393047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392c03db99c8'
down_revision: Union[str, None] = 'd44955f924a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_roles', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('person_projects', sa.Column('is_leader', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_projects', 'is_leader')
    op.drop_column('people_roles', 'notes')
    # ### end Alembic commands ###
