"""fix polymorphic relationships for decision letters and student activities

Revision ID: 6eda5eb45e1b
Revises: fbfc0d469e15
Create Date: 2025-05-16 19:57:49.485383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eda5eb45e1b'
down_revision: Union[str, None] = 'fbfc0d469e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
