"""add is_duplicate column to media and academic publication tables

Revision ID: 8c112bc6bb25
Revises: af2bb692f459
Create Date: 2026-08-06 15:03:35.476401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c112bc6bb25'
down_revision: Union[str, None] = 'af2bb692f459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_duplicate', sa.Boolean(), nullable=True))

    with op.batch_alter_table('automation_logs', schema=None) as batch_op:
        batch_op.alter_column('status',
            existing_type=sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='actionstatus'),
            type_=sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', 'IN_PROGRESS', name='actionstatus'),
            existing_nullable=False)

        batch_op.alter_column('action_type',
            existing_type=sa.Enum('MEDIA_INGESTION_RETRIEVER', 'MEDIA_INGESTION_FACTIVA',
                                  'MEDIA_PROCESSING', 'MEDIA_PUBLISH', 'ACADEMIC_SYNC',
                                  'ACADEMIC_PROCESSING', name='actiontype'),
            type_=sa.Enum('MEDIA_INGESTION_RETRIEVER', 'MEDIA_INGESTION_FACTIVA', 'MEDIA_PROCESSING',
                          'MEDIA_PUBLISH', 'ACADEMIC_SYNC', 'ACADEMIC_PROCESSING', 'ACADEMIC_PUBLISH',
                          name='actiontype'),
            existing_nullable=False)

    with op.batch_alter_table('media_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_duplicate', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_publications', schema=None) as batch_op:
        batch_op.drop_column('is_duplicate')

    with op.batch_alter_table('automation_logs', schema=None) as batch_op:
        batch_op.alter_column('status',
            existing_type=sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', 'IN_PROGRESS', name='actionstatus'),
            type_=sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='actionstatus'),
            existing_nullable=False)

        batch_op.alter_column('action_type',
            existing_type=sa.Enum('MEDIA_INGESTION_RETRIEVER', 'MEDIA_INGESTION_FACTIVA',
                                  'MEDIA_PROCESSING', 'MEDIA_PUBLISH', 'ACADEMIC_SYNC',
                                  'ACADEMIC_PROCESSING', 'ACADEMIC_PUBLISH', name='actiontype'),
            type_=sa.Enum('MEDIA_INGESTION_RETRIEVER', 'MEDIA_INGESTION_FACTIVA', 'MEDIA_PROCESSING',
                          'MEDIA_PUBLISH', 'ACADEMIC_SYNC', 'ACADEMIC_PROCESSING', name='actiontype'),
            existing_nullable=False)

    with op.batch_alter_table('academic_publications', schema=None) as batch_op:
        batch_op.drop_column('is_duplicate')

    # ### end Alembic commands ###
