"""postdocs: is_outgoing -> is_incoming, new column: link

Revision ID: 902975aaba8d
Revises: ba8212270f79
Create Date: 2025-08-18 23:40:29.513409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902975aaba8d'
down_revision: Union[str, None] = 'ba8212270f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postdocs', sa.Column('is_incoming', sa.Boolean(), nullable=True))
    op.add_column('postdocs', sa.Column('link', sa.String(), nullable=True))
    op.drop_column('postdocs', 'is_outgoing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postdocs', sa.Column('is_outgoing', sa.BOOLEAN(), nullable=True))
    op.drop_column('postdocs', 'link')
    op.drop_column('postdocs', 'is_incoming')
    # ### end Alembic commands ###
