"""add new tables for media and academic publications

Revision ID: a63f5cfa2ac4
Revises: 230dea8df773
Create Date: 2026-07-23 16:12:57.504496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63f5cfa2ac4'
down_revision: Union[str, None] = '230dea8df773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swepub_id', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_type', sa.String(), nullable=True),
    sa.Column('journal_name', sa.String(), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('authors_raw', sa.Text(), nullable=True),
    sa.Column('funding_info', sa.Text(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('is_pushed_to_wp', sa.Boolean(), nullable=False),
    sa.Column('wp_post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_publications_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_publications_swepub_id'), ['swepub_id'], unique=True)

    op.create_table('media_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('RETRIEVER', 'FACTIVA', name='mediaplatform'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('content_url', sa.String(), nullable=True),
    sa.Column('article_body', sa.Text(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('is_pushed_to_wp', sa.Boolean(), nullable=False),
    sa.Column('wp_post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_media_platform_external_id')
    )
    with op.batch_alter_table('media_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_publications_external_id'), ['external_id'], unique=False)

    op.create_table('academic_publication_person_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_publication_id', sa.Integer(), nullable=False),
    sa.Column('person_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_publication_id'], ['academic_publications.id'], ),
    sa.ForeignKeyConstraint(['person_role_id'], ['people_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_publication_person_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_publication_id', sa.Integer(), nullable=False),
    sa.Column('person_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_publication_id'], ['media_publications.id'], ),
    sa.ForeignKeyConstraint(['person_role_id'], ['people_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_publication_person_roles')
    op.drop_table('academic_publication_person_roles')
    with op.batch_alter_table('media_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_publications_external_id'))

    op.drop_table('media_publications')
    with op.batch_alter_table('academic_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_publications_swepub_id'))
        batch_op.drop_index(batch_op.f('ix_academic_publications_doi'))

    op.drop_table('academic_publications')
    # ### end Alembic commands ###
