"""person_projects: column is_leader removed, column is_contact_person added, column is_active added

Revision ID: add60aed75f6
Revises: 902975aaba8d
Create Date: 2025-11-21 11:12:26.430505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add60aed75f6'
down_revision: Union[str, None] = '902975aaba8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_projects', sa.Column('is_contact_person', sa.Boolean(), nullable=True, server_default=sa.text('0')))
    op.add_column('person_projects', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    op.drop_column('person_projects', 'is_leader')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_projects', sa.Column('is_leader', sa.BOOLEAN(), nullable=True))
    op.drop_column('person_projects', 'is_active')
    op.drop_column('person_projects', 'is_contact_person')
    # ### end Alembic commands ###
