"""projects: column is_affiliated removed, column final_report_submitted added; postdocs: column current_department removed, column is_outgoing added

Revision ID: ba8212270f79
Revises: bbe8b4e6fcb7
Create Date: 2025-07-16 08:11:19.149317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8212270f79'
down_revision: Union[str, None] = 'bbe8b4e6fcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postdocs', sa.Column('is_outgoing', sa.Boolean(), nullable=True))
    op.drop_column('postdocs', 'current_department')
    op.add_column('projects', sa.Column('final_report_submitted', sa.Boolean(), nullable=True))
    op.drop_column('projects', 'is_affiliated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_affiliated', sa.BOOLEAN(), nullable=True))
    op.drop_column('projects', 'final_report_submitted')
    op.add_column('postdocs', sa.Column('current_department', sa.VARCHAR(), nullable=True))
    op.drop_column('postdocs', 'is_outgoing')
    # ### end Alembic commands ###
